language: r
sudo: false
cache: packages
warnings_are_errors: true

env:
 global:
   - CRAN: https://cran.rstudio.com

r_packages:
- testthat
- rmarkdown
- covr

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
